default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: Blog_RubyOnRails_AngularJS_development
  pool: 5
  username: pguser
  password:

test:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: Blog_RubyOnRails_AngularJS_test
  pool: 5
  username: pguser
  password:

production:
  <<: *default
  database: Blog_RubyOnRails_AngularJS_production
  username: Blog_RubyOnRails_AngularJS
  password: <%= ENV['BLOG_RUBYONRAILS_ANGULARJS_DATABASE_PASSWORD'] %>
